### ISSUE TITLE
[AWS] Set up environment for Node.js with a DB instance

### ISSUE THREAD

**Issue by Surerocks** [richardperryman/NFC-Engineering-Project#1]
Create an environment on our AWS to handle our calls. Get it set up with a mock backend that can at least provide a limited functionality for testing, in Node.js for now.

Set up the DB instance to have tables that are appropriate, so we can easily do some test queries and add more data easily.

**Comment by richardperryman** [comment]
Do you want to call sometime today to set this up together?

**Comment by Surerocks** [comment]
I think I am almost done setting up the DB and environment, so I will get back to you this afternoon to come up with a time to discuss next steps and other set up

**Comment by richardperryman** [comment]
Sure let me know when you are ready.

**Comment by Surerocks** [comment]
Is 3 a good time for you?

**Comment by richardperryman** [comment]
Yep, 3 should be good

**Comment by Surerocks** [comment]
I have this working now. I have a DB and Node.js environment working on AWS, and I have installed my simple app that echos back the contents of the Users table on every GET request. Please try it out and make sure it works for you. The code has also been committed in the AWS folder, so you can see how to do the basic db stuff.

**Comment by richardperryman** [comment]
Been fiddling with this for a while, but I'm getting the same problems as yesterday with being unable to connect. Did you see my comments on Skype? I think we need to add a rule to our VPC or something so that certain IPs can connect to our server.

**Comment by Surerocks** [comment]
The VPC is probably where our problem is from, but I can't figure out what to change with it. I added something to that so that the Elastic Beanstalk application can use it, so at least that works.

**Comment by richardperryman** [comment]
For the record, I've fixed the security group issue. I was able to test both and they seem fine. The only problem was that innodb didn't exist when I ran the mock server, so I changed it to sbacsDb.

**Comment by Surerocks** [comment]
I am now unable to connect to it unfortunately. What did you do to get it to work for you?

**Comment by richardperryman** [comment]
Oh, I wrote it in Skype, I'll copy it here in just a second.

**Comment by richardperryman** [comment]
> Or if you want to fix it yourself, go to that dashboard thing, then go to VPC and then under security on the left select security groups. Then find the one in the group name "rds-launch-wizard" and select the box thing beside it. Then down below select Inbound Rules and then click edit and add a MySQL/Aurora rule and set the source to exactly your IP with a /32 after it

**Comment by Surerocks** [comment]
Awesome, thanks!
