### ISSUE TITLE
Presentation organisation

### ISSUE THREAD

**Issue by richardperryman** [richardperryman/NFC-Engineering-Project#11]
Almost forgot to do this today. Anyway I think we should try to decide how we will split up the work for the presentation. The main stuff I think we should cover is:

- The four use cases we described in the proposal
- Techhnical decisions made
- Some demonstration material

I think we should each touch on some of this? I think we could keep our assignments from the proposal with respect to the use cases. Then I would do 3.3 and 3.4, and Jess would do 3.1 and Craig would do 3.2. For the technical stuff I think we should each try to come up with 1-2 diagrams showing basically how our part works. Then the demonstrations stuff we might each have screenshots of doing something useful, and then maybe an end-to-end sample?

Let me know what you think of this.

**Comment by richardperryman** [comment]
My Gmail is: richard.jperryman@gmail.com

**Comment by jessicamorris** [comment]
Mine is jess.d.morris.94@gmail.com

**Comment by Surerocks** [comment]
Here is the link: https://docs.google.com/presentation/d/1N285FfDBTXB5dOukfdxKK701NOKU2duNCM4tosi7n6Y/edit?usp=sharing

You should both be able to use it, I added you to it. Let me know if you have problems with it.
